spring:
  cloud:
    config:
      server:
        git:
          basedir: /root/springcloud/config/basedir
eureka:
  client:
    service-url:
      defaultZone: http://eureka1:8761/eureka/,http://eureka2:8762/eureka/