eureka:
  client:
    service-url:
      defaultZone: http://eureka2:8762/eureka/
#    register-with-eureka: false
  server:
    enable-self-preservation: true
spring:
  application:
    name: eureka
management:
  server:
    servlet:
      context-path: /
server:
  port: 8761
